### ISSUE TITLE
Build issues on macOS

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#537]
This is to report some issues encountered on the way to a successful build with (largely) GCC 10.1.0 on macOS Catalina.

### Which Python? ###

I checked out 43b3ea1; I already had a clone, with a virtualenv running the system Python 2.7.16. This resulted in
```
(venv) lockheed:libadalang simon$ python --version
Python 2.7.16
(venv) lockheed:libadalang simon$ python ada/manage.py make
  File "ada/manage.py", line 320
    print(text, file=f)
                    ^
SyntaxError: invalid syntax
```
which I take to mean I need to use Python 3 - I have 3.7.
The build instructions don't specify, but they do quote a 2.7 command `virtualenv env` instead of the 3 command `python3 -m venv env`.

### Installing the required Python environment ###

pip install -r REQUIREMENTS.dev failed with
```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=570 -DPSUTIL_OSX=1 -I/Users/simon/adacore/libadalang/venv/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c psutil/_psutil_osx.c -o build/temp.macosx-10.9-x86_64-3.7/psutil/_psutil_osx.o
psutil/_psutil_osx.c:36:10: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
   36 | #include <CoreFoundation/CoreFoundation.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Suspecting this might be a gcc issue with macOS Frameworks, ran
```
CC=clang pip install psutil
```
which worked immediately, followed by
```
pip install -r REQUIREMENTS.dev
```
which worked immediately. I expect I could have used `CC=clang` from the start.

### Generate ###

`python ada/manage.py generate` failed with
```
gnatpp: invalid switch : --syntax-only
try "gnatpp --help" for more information.
Pretty-printing failed: error while running gnatpp -P/Users/simon/adacore/libadalang/build/src/mains.gpr --syntax-only --eol=lf -XBUILD_MODE=dev -XLIBRARY_TYPE=relocatable -XGPR_BUILD=relocatable -XXMLADA_BUILD=relocatable /Users/simon/adacore/libadalang/build/src/parse.adb:
    Command '['gnatpp', '-P/Users/simon/adacore/libadalang/build/src/mains.gpr', '--syntax-only', '--eol=lf', '-XBUILD_MODE=dev', '-XLIBRARY_TYPE=relocatable', '-XGPR_BUILD=relocatable', '-XXMLADA_BUILD=relocatable', '/Users/simon/adacore/libadalang/build/src/parse.adb']' returned non-zero exit status 1.
Generation complete!
```
because the `gnatpp` I'm running with GCC 10.1.0 is still the old ASIS-based version that doesn't understand `--syntax-only`; so try that command line with the one from GNAT CE 2020; OK.
Of course, this wasn't strictly necessary, since it's just tidying up at the very end.

### Build ###

This failed with
```
   [C]            libadalang_quex_interface.c
In file included from /Users/simon/adacore/libadalang/build/include/libadalang/libadalang_lexer.h:36,
                 from /Users/simon/adacore/libadalang/build/include/libadalang/libadalang_lexer.c:2:
/Users/simon/adacore/libadalang/build/include/libadalang/libadalang_lexer-configuration.h:395:10: fatal error: quex/code_base/analyzer/configuration/derived: No such file or directory
  395 | #include <quex/code_base/analyzer/configuration/derived>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
After some puzzlement I realised that you no longer need us to have QUEX installed.

If there was an **`ada/manage.py clean` option** that might have been the answer, but my workround was to clone a clean copy; result, **SUCCESS**!

**Comment by pmderodat** [comment]
Hello @simonjwright,

> which I take to mean I need to use Python 3 - I have 3.7.

That’s correct: we now require Python3 in order to build Libadalang.

> The build instructions don't specify, but they do quote a 2.7 command `virtualenv env` instead of the 3 command `python3 -m venv env`.

Virtualenv also works with Python3, and this is what we use ourselves. Besides, depending on the environment, there may be no `python3`/`pip3`/`virtualenv3`/… programs when a Python3 distribution is installed.

So commands such as:
```
virtualenv env
```
don’t necessarily imply Python2. Is this what you meant?

> which worked immediately. I expect I could have used `CC=clang` from the start.

Good to know that you have a workaround.

> `python ada/manage.py generate` failed with
> 
> ```
> gnatpp: invalid switch : --syntax-only
> […]
> ```
> 
> because the `gnatpp` I'm running with GCC 10.1.0 is still the old ASIS-based version that doesn't understand `--syntax-only`; so try that command line with the one from GNAT CE 2020; OK.

You can disable pretty-printing of the generated sources thanks the `-P` option:
```
python ada/manage.py generate -P
```

> This failed with
> 
> ```
>    [C]            libadalang_quex_interface.c
> […]
> ```
> 
> After some puzzlement I realised that you no longer need us to have QUEX installed.

Yes, we should probably make Langkit remove files left from previous compilations to avoid this issue in the future.

> If there was an **`ada/manage.py clean` option** that might have been the answer, but my workround was to clone a clean copy; result, **SUCCESS**!

Starting from a fresh clone looks overkill: you can also remove the `build` subdirectory (which contains all build artifacts, and only them).

Thank you for sharing your experiments. We’ll keep this issue open to address the issue of leftover sources hindeling the build process.

**Comment by simonjwright** [comment]
> Hello @simonjwright,
> 
> > which I take to mean I need to use Python 3 - I have 3.7.
> 
> That’s correct: we now require Python3 in order to build Libadalang.

I’m pretty sure the build instructions don’t say so.

> > The build instructions don't specify, but they do quote a 2.7 command `virtualenv env` instead of the 3 command `python3 -m venv env`.
> 
> Virtualenv also works with Python3, and this is what we use ourselves. Besides, depending on the environment, there may be no `python3`/`pip3`/`virtualenv3`/… programs when a Python3 distribution is installed.
> 
> So commands such as:
> 
> ```
> virtualenv env
> ```
> 
> don’t necessarily imply Python2. Is this what you meant?

It was, because I couldn’t see how to get my Python3 to accept virtualenv, and the `-m venv` approach seemed to be the recommended one.

> You can disable pretty-printing of the generated sources thanks the `-P` option:
> 
> ```
> python ada/manage.py generate -P
> ```

Thanks

> Starting from a fresh clone looks overkill: you can also remove the `build` subdirectory (which contains all build artifacts, and only them).

I tried this afterwards, works fine as you say.

**Comment by pmderodat** [comment]
Understood, thank you. We will rework the Setup section to use `python -mvenv` instead of `virtualenv`, as it’s indeed recommended officially, and then close this issue, assuming everything is properly addressed. Please let us know if not. :-)
